#!/bin/sh
#
# DKIM2-core modifying re-sign integration test (experimental; requires
# WITH_DKIM2)

if [ x"$srcdir" = x"" ]
then
	srcdir=`pwd`
fi

../../miltertest/miltertest $MILTERTESTFLAGS -s $srcdir/t-dkim2-resign.lua
